### ISSUE TITLE
Symbol

### ISSUE THREAD

**Issue by dsebastien** [andrew-w-ross/typings-redux#1]
Hello,

I've installed your typings, but when I run tsc, it complains about the usage of "Symbol".
Should I install other typings first?

**Comment by lhahne** [comment]
Same issue here.

**Comment by silviogutierrez** [comment]
I have this issue too.

**Comment by andrew-w-ross** [comment]
@dsebastien, @lhahne , @silviogutierrez  Sorry for getting back to you three so late, I assume you're targeting es5?

**Comment by dsebastien** [comment]
yep
