### ISSUE TITLE
Perparing for official redux typings?

### ISSUE THREAD

**Issue by Ciantic** [andrew-w-ross/typings-redux#3]
Redux will get official typings in next version:
https://github.com/reactjs/redux/blob/master/index.d.ts

I think this repository could prepare for this by starting to use same names, e.g. ReducersMapObject instead of IReducerMap.

Notice that once Redux 4 is released, the official typings work automatically because TypeScript is made to look at package.json for typings tag. 

So this community typing will be deprecated, it would be just helpful if one could start preparing for this change.

**Comment by Ciantic** [comment]
Oops, last time I looked they were in next branch. They are already in master, I thought they were supposed to appear in next major release. Well then, this is already deprecated in that case.

**Comment by andrew-w-ross** [comment]
@Ciantic Hey sorry for taking so long to reply. You're right this repository should be deprecated. The bigger issue is getting the redux typings into the typings registry and then referencing those typings. I'll see what can be done.

**Comment by andrew-w-ross** [comment]
I've added a deprecation notice.
